<?php

namespace AppBundle\Repository;

/**
 * ExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExams($keyword) {
        
        $qb = $this->createQueryBuilder("a");

        $qb->select("a");

        if($keyword != "all") {
            $qb->andWhere("a.titre LIKE :keyword OR a.code LIKE :keyword ")->setParameter("keyword", "%".$keyword."%");
        }

        return $qb->getQuery()->getResult();

    }
}
