# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  service:
          class: AppBundle\Services\ServiceRecherche
          arguments: [ '@doctrine.orm.entity_manager' ]

  console_command.csv_import:
      class: AppBundle\Command\CsvImportCommand
      arguments:
          - "@doctrine.orm.entity_manager"
      tags:
          - { name: console.command }